const actionsTypes = {
  CREATE_FILE: 'CREATE_FILE',
  DELETE_FILE: 'DELETE_FILE',
  ADD_FILE_TO_TABS: 'ADD_FILE_TO_TABS',
  REMOVE_FILE_FROM_TABS: 'REMOVE_FILE_FROM_TABS',
  FOCUS_ON_FILE: 'FOCUS_ON_FILE',
};

export default actionsTypes;
